apiVersion: apps/v1
kind: Deployment
metadata:
  name: mondodb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mondodb
  template:
    metadata:
      labels:
        app: mondodb
    spec:
      containers:
        - name: mondodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongouser"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "mongopwd"
          resources: {}
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
