apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedelogo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedelogo
  template:
    metadata:
      labels:
        app: pedelogo
    spec:
      containers:
        - name: pedelogo
          image: fabricioveronez/pedelogo-catalogo:v1
          ports:
            - containerPort: 80
          env:
            - name: Mongo__Host
              value: "mondodb-svc"
            - name: Mongo__User
              value: "mongouser"
            - name: Mongo__Password
              value: "mongopwd"
            - name: Mongo__Port
              value: "27017"
            - name: Mongo__DataBase
              value: "admin"
          resources: {}
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
